### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by wdsongama** [the-database/traiNNer-redux#109]
Traceback (most recent call last):
  File "C:\Users\wdson\Downloads\Compressed\traiNNer-redux-master\train.py", line 29, in <module>
    from traiNNer.models import build_model
  File "C:\Users\wdson\Downloads\Compressed\traiNNer-redux-master\traiNNer\models\__init__.py", line 4, in <module>
    from traiNNer.models.realesrgan_model import RealESRGANModel
  File "C:\Users\wdson\Downloads\Compressed\traiNNer-redux-master\traiNNer\models\realesrgan_model.py", line 16, in <module>
    from traiNNer.models.sr_model import SRModel
  File "C:\Users\wdson\Downloads\Compressed\traiNNer-redux-master\traiNNer\models\sr_model.py", line 22, in <module>
    from traiNNer.losses import build_loss
  File "C:\Users\wdson\Downloads\Compressed\traiNNer-redux-master\traiNNer\losses\__init__.py", line 28, in <module>
    importlib.import_module(f"traiNNer.losses.{file_name}")
  File "C:\Users\wdson\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wdson\Downloads\Compressed\traiNNer-redux-master\traiNNer\losses\hr_inversion_loss.py", line 13, in <module>
    from timm.models.registry import register_model
  File "C:\Users\wdson\Downloads\Compressed\traiNNer-redux-master\venv\Lib\site-packages\timm\models\registry.py", line 1, in <module>
    from ._registry import *
AttributeError: module 'timm.models._registry' has no attribute 'get_pretrained_cfgs_for_arch'. Did you mean: 'get_pretrained_cfg_value'?

**Comment by the-database** [comment]
This is fixed by #110
